/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductoDto } from '../../models/producto-dto';

export interface ApiParametrosProductosGet$Params {
}

export function apiParametrosProductosGet(http: HttpClient, rootUrl: string, params?: ApiParametrosProductosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductoDto>>> {
  const rb = new RequestBuilder(rootUrl, apiParametrosProductosGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductoDto>>;
    })
  );
}

apiParametrosProductosGet.PATH = '/api/parametros/productos';
