/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiParametrosClientesGet$Params } from './fn/parametros/api-parametros-clientes-get';
export { apiParametrosClientesGet } from './fn/parametros/api-parametros-clientes-get';
export type { ApiParametrosProductosGet$Params } from './fn/parametros/api-parametros-productos-get';
export { apiParametrosProductosGet } from './fn/parametros/api-parametros-productos-get';
export type { ApiParametrosEstadosGet$Params } from './fn/parametros/api-parametros-estados-get';
export { apiParametrosEstadosGet } from './fn/parametros/api-parametros-estados-get';
export type { ApiPedidosPost$Params } from './fn/pedidos/api-pedidos-post';
export { apiPedidosPost } from './fn/pedidos/api-pedidos-post';
