/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ClienteDto } from './models/cliente-dto';
export type { CrearPedidoDto } from './models/crear-pedido-dto';
export type { DetallePedidoDto } from './models/detalle-pedido-dto';
export type { DetallePedidoDtoRep } from './models/detalle-pedido-dto-rep';
export type { EstadoDto } from './models/estado-dto';
export type { PedidoDto } from './models/pedido-dto';
export type { ProductoDto } from './models/producto-dto';
