/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PedidoDto } from '../../models/pedido-dto';

export interface ApiPedidosGet$Params {
}

export function apiPedidosGet(http: HttpClient, rootUrl: string, params?: ApiPedidosGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PedidoDto>>> {
  const rb = new RequestBuilder(rootUrl, apiPedidosGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PedidoDto>>;
    })
  );
}

apiPedidosGet.PATH = '/api/pedidos';
