/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClienteDto {
  direccion?: string | null;
  id?: number;
  identificacion?: string | null;
  nombre?: string | null;
  telefono?: string | null;
}
