/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DetallePedidoDto } from '../models/detalle-pedido-dto';
export interface CrearPedidoDto {
  clienteId?: number;
  creadoPor?: string | null;
  direccionEntrega?: string | null;
  productos?: Array<DetallePedidoDto> | null;
}
