/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DetallePedidoDtoRep {
  dpP_Cantidad?: number;
  dpP_IdDetalle?: number;
  prO_IdProducto?: number;
  productoNombre?: string | null;
  valorTotalDetalle?: number;
  valorUnitario?: number;
}
