/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DetallePedidoDtoRep } from '../models/detalle-pedido-dto-rep';
export interface PedidoDto {
  clI_IdCliente?: number;
  clienteNombre?: string | null;
  detallePedidos?: Array<DetallePedidoDtoRep> | null;
  esT_IDEstado?: number;
  estadoNombre?: string | null;
  peD_DireccionEntrega?: string | null;
  peD_FechaRegistro?: string;
  peD_IdPedido?: number;
  peD_ValorParcialoTotal?: number;
  prI_IdPrioridad?: number;
  prioridadNombre?: string | null;
}
