/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductoDto {
  codigo?: string | null;
  id?: number;
  nombre?: string | null;
  valorUnitario?: number;
}
